name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }} # Используйте PAT для аутентификациио

      - name: Configure Git
        run: |
          git config user.name Maaaaxim
          git config user.email maxim.kubichka@gmail.com

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            cd /home/sc527094/calories365.space/calculator
            git config --global user.name "Maaaaxim"
            git config --global user.email "maxim.kubichka@gmail.com"
            git config --global credential.helper store
            git pull https://Maaaaxim:${{ secrets.PAT }}@github.com/Maaaaxim/Calories365.git
            composer install
            php artisan migrate

