name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-scripts --no-progress --no-suggest

      - name: Install Node.js dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Указывает на каталог с файлами для загрузки
          remote-dir: ${{ secrets.FTP_PATH }} # Путь на FTP сервере, куда будут загружаться файлы
          # Включаем удаление файлов в целевом каталоге, которых нет в репозитории
          dangerous-clean-slate: false
